### ISSUE TITLE
Problems with blend_multiple composition on last layer

### ISSUE THREAD

**Issue by joamag** [ripe-tech/pconvert-rust#11]
## Description

Blending multiple seems to not be working correctly for the last layer (in this case the buckle at the front of the shoe).

Use your local RIPE Core deployment and the following URL.

http://localhost:8181/test/config/render?brand=sergio_rossi&model=sr1_pump105&initials_algorithm=destination_over&initials_debug=1&cache=0&crop=1#composition-large

## Expected vs. Observed

| - | - |
| --- | --- |
| **Expected** | The Last layer should be able to be properly composed. |
| **Observed** | The last layer is not display in the image. |

## Screens

<img width="1230" alt="Screenshot 2020-09-10 at 18 52 42" src="https://user-images.githubusercontent.com/25441/92776304-0c49dd00-f397-11ea-9db6-9d887b148def.png">

<img width="1014" alt="Screenshot 2020-09-10 at 18 56 06" src="https://user-images.githubusercontent.com/25441/92776608-5468ff80-f397-11ea-831b-47a8f7a3965a.png">

**Comment by joao-conde** [comment]
@joamag I found the [issue](https://github.com/ripe-tech/pconvert-rust/blob/master/src/pymodule.rs#L99). I am skipping the first algorithm to use, hence my "zip" iteration ends one step sooner, not blending the last layer.

**Comment by joamag** [comment]
Off by one errors... A classic!
