### ISSUE TITLE
When using initials in a composition a TypeError is raised

### ISSUE THREAD

**Issue by joamag** [ripe-tech/pconvert-rust#13]
## Description

To repro this issue, install the sergio_rossi build (`rbm install sergio_rossi`) and use the following URL:

http://localhost:8181/compose?brand=sergio_rossi&model=sr1_pump105&initials=TOP&initials_algorithm=destination_over&initials_debug=1&cache=0&crop=1

## Screens

<img width="980" alt="Screenshot 2020-09-10 at 19 00 00" src="https://user-images.githubusercontent.com/25441/92777161-db1ddc80-f397-11ea-8229-2787d4e0f91a.png">

**Comment by joamag** [comment]
Seem that this is another of the list/tuple vs sequence type of issue

**Comment by joamag** [comment]
@joao-conde found it, the algorithms sequence can be a sequence of strings or tuples. If using the tuples (sequence) it can be used to configure the blending algorithm with some options

The screen below is a capture of the parameters for compositions with and without initials

<img width="1170" alt="Screenshot 2020-09-10 at 19 04 07" src="https://user-images.githubusercontent.com/25441/92777961-9e061a00-f398-11ea-8a15-c6c7de55e914.png">

**Comment by joao-conde** [comment]
These are the so called "extra parameters" in the C code then? I forgot them at the time. If these are those parameters it is good to see a use-case like this, thanks. I will work on it first thing in the morning.

**Comment by joao-conde** [comment]
@joamag  the way I interpret this is then the following (correct me if wrong):

- in this composition there are 5 images (5 paths provided)
- this means we perform 4 blending operations
- all of the 4 blending operations use the destination_over algorithm
- the last tuple `(destination_over, ('factor', 1.0))` indicates that FOR ALL `destination_over` algorithms a `factor` of 1.0 will be applied

Am I correct to assume that if `(algorithm, (key, value))` is given then to all algorithms of type `algorithm` I use `value` for some algorithm property `key`?

**Comment by joamag** [comment]
> @joamag the way I interpret this is then the following (correct me if wrong):
> 
> * in this composition there are 5 images (5 paths provided)
> * this means we perform 4 blending operations
> * all of the 4 blending operations use the destination_over algorithm
> * the last tuple `(destination_over, ('factor', 1.0))` indicates that FOR ALL `destination_over` algorithms a `factor` of 1.0 will be applied
> 
> Am I correct to assume that if `(algorithm, (key, value))` is given then to all algorithms of type `algorithm` I use `value` for some algorithm property `key`?

The `algorithms` is used to control each of the blending operations independently (individually) so that a specific blending algorithm can be used for one of the blends meaning that for instance in the example above only the last blend operation will have the factor 1.0 option applied.

As for the schema of the `algorithms` parameter, it should be either a simple string indicating the algorithm to be used with the pre-defined options or a tuple of a string and sequence of tuples that define the name of the algorithm and the multiple key, value pairs for options (parameters) to be used in the algorithm eg: `("destination_over", (("factor", 1.0), ("tobias", True)))`. Important to note that the key.

The parsing of these extra parameters is done here https://github.com/hivesolutions/pconvert/blob/c6ae2c65181e55bea59235e7ce14f2e6ab6835fb/src/pconvert/extension.c#L5 (converting the parameters in python to parameters in the internal blending format) special note to the fact that the value can assume multiple data types, there's explicit data type checking.

Then it is used here  https://github.com/hivesolutions/pconvert/blob/c6ae2c65181e55bea59235e7ce14f2e6ab6835fb/src/pconvert/extension.c#L421 to apply different algorithms and options to each blend operations.

**Comment by joao-conde** [comment]
> > @joamag the way I interpret this is then the following (correct me if wrong):
> > 
> > * in this composition there are 5 images (5 paths provided)
> > * this means we perform 4 blending operations
> > * all of the 4 blending operations use the destination_over algorithm
> > * the last tuple `(destination_over, ('factor', 1.0))` indicates that FOR ALL `destination_over` algorithms a `factor` of 1.0 will be applied
> > 
> > Am I correct to assume that if `(algorithm, (key, value))` is given then to all algorithms of type `algorithm` I use `value` for some algorithm property `key`?
> 
> The `algorithms` is used to control each of the blending operations independently (individually) so that a specific blending algorithm can be used for one of the blends meaning that for instance in the example above only the last blend operation will have the factor 1.0 option applied.
> 
> As for the schema of the `algorithms` parameter, it should be either a simple string indicating the algorithm to be used with the pre-defined options or a tuple of a string and sequence of tuples that define the name of the algorithm and the multiple key, value pairs for options (parameters) to be used in the algorithm eg: `("destination_over", (("factor", 1.0), ("tobias", True)))`. Important to note that the value can have multiple data types.
> 
> The parsing of these extra parameters is done here https://github.com/hivesolutions/pconvert/blob/c6ae2c65181e55bea59235e7ce14f2e6ab6835fb/src/pconvert/extension.c#L5 (converting the parameters in python to parameters in the internal blending format) special note to the fact that the value can assume multiple data types, there's explicit data type checking.
> 
> Then it is used here https://github.com/hivesolutions/pconvert/blob/c6ae2c65181e55bea59235e7ce14f2e6ab6835fb/src/pconvert/extension.c#L421 to apply different algorithms and options to each blend operation.

Ok I understand it. However in the example given (your print screen) there are 5 images i.e. 4 blending operations. But the last tuple is a 5th algorithm, which I didn't expect
