### ISSUE TITLE
Disjoint Over blending algorithm with incorrect output

### ISSUE THREAD

**Issue by joao-conde** [ripe-tech/pconvert-rust#3]
## Description

The disjoint over blending algorithm produces compositions (with the assets/demo/ files) that differ from the original PConvert output.

## Expected vs. Observed

| - | - |
| --- | --- |
| **Expected** | Have equal compositions to the original PConvert. |
| **Observed** | The compositions using disjoint over blending are different. |

## Repro Steps

1. Compile and install the original PConvert in your machine
2. Invoke ```pconvert compose assets/demo/```
3. Compile and install this repository (PConvert-rust)
4. Invoke ```pconvert compose assets/demo/```

## Environment

| Key | Value |
| --- | --- |
| **Operating System** |  Manjaro |

**Comment by joamag** [comment]
Closing this as won't fix as this is not relevant for business.
