### ISSUE TITLE
Remove the tests coded as command line functionalities and properly encode them as unit tests

### ISSUE THREAD

**Issue by joao-conde** [ripe-tech/pconvert-rust#4]
## Rationale

Implementing the tests as actual unit tests rather than a command line utility of pconvert will not only be more idiomatic and semantically correct but also allow us to run `cargo test` to run our unit tests. Thus, we can apply this with our CI systems.

## Description

Removes the `compose` calls in the `pconvert compose` utility and separates them into test files.

## Implementation

1. Create a test file (e.g. `tests.rs`)
2. Copy and paste the compose calls to this file.
3. Make use of assertions versus previously computed outputs (our ground-truth)

## Estimation

| Discipline | Estimation |
| --- | --- |
| **UI/UX Design** | 0 days |
| **Software Development** | 1 days |

**Comment by joamag** [comment]
@joao-conde Let's move ahead with this "conversion", let's just not remove the other tests and instead just add new ones as unit tests
