### ISSUE TITLE
Rust Trademark Policy Compliance

### ISSUE THREAD

**Issue by joao-conde** [ripe-tech/pconvert-rust#54]
The Rust Foundation is considering to enforce the following trademark policy: https://docs.google.com/document/d/1ErZlwz9bbSI43dNo-rgQdkovm2h5ycuW220mWSOAuok/edit

The following states many potentially copyright infringements, but since this crate is open source must do not apply.

However, it is worth noting the following:

> "Can I use the word “Rust” in the name of one of my crates?
The Project would like the word Rust in a crate name to imply ownership by the Project. You should generally use ‘-rs’ instead in this situation. Please see “Use of the marks in toolchains or other software for use with Rust” section."

If this trademark does go through, we should have someone review it and make the necessary changes to this crate, starting by the name (renaming to pconvert-rs).

**Comment by simaob** [comment]
Hey, 
Yesterday I saw on twitter something about this and that some members of the Rust community weren't particularly happy with the draft proposed by the Rust Foundation. So it might be a bit early to act on it. But we definitely should keep tabs on the outcome of this effort on their side.

**Comment by joao-conde** [comment]
Definitely early, yeah, the trademark is just a draft I think. Everyone is really unhappy about it. Hopefully we can close this without taking any action but I opened it so that we don't forget.
